trainer: basic 
output_dir: $SCRATCH/mlreco_cell/sparse_singleMu
eval_out: True

data:
    name: sparse
    data_path: $SCRATCH/larsim/reco_1GeV_xy
    n_train: 125
    n_valid: 1 
    batch_size: 1 
model:
    name: cellnet_sparse
    spatial_size: [1024, 1024, 512]
    nChannels: 8
    nStrides: 4
    n_2D: 2

loss: 
    name: MSELoss 
optimizer:
    name: Adam
    lr: 0.001
train:
    n_epochs: 1000
