trainer: basic 
output_dir: $SCRATCH/mlreco_cell/sparse_singleElectronHit_ghost2D_1652
store_inference: 
#outdir: inf_train
    everyNepoch: 2
    everyNsample: 5

data:
    name: sparse
    data_path: $SCRATCH/larsim/reco_1GeV_ElectronHit_xy
    train_i: [1, 100]
    inference_i: [101, 150]
    #train_i: [1, 1]
    #inference_i: [1, 3]
    batch_size: 1 
    threshold: 0.001
model:
    name: cellnet_binary
    spatial_size: [1024, 1024, 512]
    nChannels: 16
    nStrides: 5
    n_2D: 2
    reps: 2

loss: 
    name: BCELoss 

optimizer:
    name: Adam
    lr: 0.001
train:
    n_epochs: 1000
metrics:
    acc: BinAccuracy
