trainer: basic 
output_dir: $SCRATCH/mlreco_cell/singleElectronWire_ghost3D-164

store_inference:
#outdir: inf_pion
    everyNepoch: 2
    everyNsample: 5

data:
    name: sparse
    data_path: $SCRATCH/larsim/reco_1GeV_ElectronWire_xy
    train_i: [1, 100]
    inference_i: [101, 150]
    #inference_i: [0, 10]
    batch_size: 1 
    threshold: 0.001
model:
    name: cellnet_binary
    spatial_size: [1024, 1024, 512]
    nChannels: 16
    nStrides: 4
    n_2D: 0
    downsample_t: [2, 2]

loss: 
    name: BCELoss 

optimizer:
    name: Adam
    lr: 0.001
train:
    n_epochs: 1000
metrics:
    acc: BinAccuracy
