trainer: basic 
output_dir: $SCRATCH/mlreco_cell/singleElectronHit_ghost3D-164

store_inference: 
    outdir: inf_train

data:
    name: sparse
    data_path: $SCRATCH/larsim/reco_1GeV_ElectronHit_xy
    inference_i: [1, 3]
    batch_size: 1 
    threshold: 0.001

model:
    name: cellnet_binary
    spatial_size: [1024, 1024, 512]
    nChannels: 16
    nStrides: 4
    n_2D: 0
    downsample_t: [2, 2]

loss: 
    name: BCEL1Loss 
    L1_lambda: 0.1
optimizer:
    name: Adam
    lr: 0.001
train:
    n_epochs: 1000
metrics:
    acc: BinAccuracy
